version: '3.8'

services:
  db:
    container_name: app-api-db
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      TZ: "Europe/Madrid"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    env_file: ./.env
